#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user on port 8080.

# Install Nginx if it's not already installed
apt-get -y install nginx

# Modify Nginx configuration to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Make Nginx listen on port 8080 for all IPs
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
service nginx restart
