#!/bin/bash

# Create an nginx user if it doesn't exist
if ! getent passwd nginx > /dev/null 2&>1; then
  useradd -r nginx
fi

# Update Nginx configuration to run as nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
