#!/bin/bash
# Run Nginx as the nginx user and listen on port 8080

# Modify the Nginx configuration file to set user to nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Modify the Nginx default site to listen on port 8080
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Remove the default Nginx site symlink from sites-enabled
rm /etc/nginx/sites-enabled/default

# Create a new symlink to the default site in sites-enabled
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test the Nginx configuration
nginx -t

# Restart Nginx
service nginx restart
